// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: rpc/Abnormal.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AbnormalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnomalyScore      float32 `protobuf:"fixed32,1,opt,name=anomaly_score,json=anomalyScore,proto3" json:"anomaly_score,omitempty"`
	AnomalyCameraName string  `protobuf:"bytes,2,opt,name=anomaly_camera_name,json=anomalyCameraName,proto3" json:"anomaly_camera_name,omitempty"`
}

func (x *AbnormalResponse) Reset() {
	*x = AbnormalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_Abnormal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbnormalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbnormalResponse) ProtoMessage() {}

func (x *AbnormalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_Abnormal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbnormalResponse.ProtoReflect.Descriptor instead.
func (*AbnormalResponse) Descriptor() ([]byte, []int) {
	return file_rpc_Abnormal_proto_rawDescGZIP(), []int{0}
}

func (x *AbnormalResponse) GetAnomalyScore() float32 {
	if x != nil {
		return x.AnomalyScore
	}
	return 0
}

func (x *AbnormalResponse) GetAnomalyCameraName() string {
	if x != nil {
		return x.AnomalyCameraName
	}
	return ""
}

type AbnormalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CameraName []string `protobuf:"bytes,1,rep,name=camera_name,json=cameraName,proto3" json:"camera_name,omitempty"`
	RtspUrl    []string `protobuf:"bytes,2,rep,name=rtsp_url,json=rtspUrl,proto3" json:"rtsp_url,omitempty"`
}

func (x *AbnormalRequest) Reset() {
	*x = AbnormalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_Abnormal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbnormalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbnormalRequest) ProtoMessage() {}

func (x *AbnormalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_Abnormal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbnormalRequest.ProtoReflect.Descriptor instead.
func (*AbnormalRequest) Descriptor() ([]byte, []int) {
	return file_rpc_Abnormal_proto_rawDescGZIP(), []int{1}
}

func (x *AbnormalRequest) GetCameraName() []string {
	if x != nil {
		return x.CameraName
	}
	return nil
}

func (x *AbnormalRequest) GetRtspUrl() []string {
	if x != nil {
		return x.RtspUrl
	}
	return nil
}

type AbnormalFlagParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag bool `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *AbnormalFlagParam) Reset() {
	*x = AbnormalFlagParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_Abnormal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbnormalFlagParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbnormalFlagParam) ProtoMessage() {}

func (x *AbnormalFlagParam) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_Abnormal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbnormalFlagParam.ProtoReflect.Descriptor instead.
func (*AbnormalFlagParam) Descriptor() ([]byte, []int) {
	return file_rpc_Abnormal_proto_rawDescGZIP(), []int{2}
}

func (x *AbnormalFlagParam) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

type ChangeFlagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   bool   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ChangeFlagResponse) Reset() {
	*x = ChangeFlagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_Abnormal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeFlagResponse) ProtoMessage() {}

func (x *ChangeFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_Abnormal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeFlagResponse.ProtoReflect.Descriptor instead.
func (*ChangeFlagResponse) Descriptor() ([]byte, []int) {
	return file_rpc_Abnormal_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeFlagResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ChangeFlagResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_Abnormal_proto protoreflect.FileDescriptor

var file_rpc_Abnormal_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x70, 0x63, 0x2f, 0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x10, 0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6e, 0x6f, 0x6d,
	0x61, 0x6c, 0x79, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0c, 0x61, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x2e, 0x0a,
	0x13, 0x61, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x5f, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61, 0x6e, 0x6f, 0x6d,
	0x61, 0x6c, 0x79, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4d, 0x0a,
	0x0f, 0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x74, 0x73, 0x70, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x72, 0x74, 0x73, 0x70, 0x55, 0x72, 0x6c, 0x22, 0x27, 0x0a, 0x11,
	0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x46, 0x6c, 0x61, 0x67, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x44, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x46,
	0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x89, 0x01, 0x0a, 0x11,
	0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x33, 0x0a, 0x08, 0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x12, 0x10, 0x2e,
	0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3f, 0x0a, 0x12, 0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d,
	0x61, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x12, 0x2e, 0x41,
	0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x46, 0x6c, 0x61, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x1a, 0x13, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_Abnormal_proto_rawDescOnce sync.Once
	file_rpc_Abnormal_proto_rawDescData = file_rpc_Abnormal_proto_rawDesc
)

func file_rpc_Abnormal_proto_rawDescGZIP() []byte {
	file_rpc_Abnormal_proto_rawDescOnce.Do(func() {
		file_rpc_Abnormal_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_Abnormal_proto_rawDescData)
	})
	return file_rpc_Abnormal_proto_rawDescData
}

var file_rpc_Abnormal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_Abnormal_proto_goTypes = []interface{}{
	(*AbnormalResponse)(nil),   // 0: AbnormalResponse
	(*AbnormalRequest)(nil),    // 1: AbnormalRequest
	(*AbnormalFlagParam)(nil),  // 2: AbnormalFlagParam
	(*ChangeFlagResponse)(nil), // 3: ChangeFlagResponse
}
var file_rpc_Abnormal_proto_depIdxs = []int32{
	1, // 0: AbnormalDetection.Abnormal:input_type -> AbnormalRequest
	2, // 1: AbnormalDetection.AbnormalChangeFlag:input_type -> AbnormalFlagParam
	0, // 2: AbnormalDetection.Abnormal:output_type -> AbnormalResponse
	3, // 3: AbnormalDetection.AbnormalChangeFlag:output_type -> ChangeFlagResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_Abnormal_proto_init() }
func file_rpc_Abnormal_proto_init() {
	if File_rpc_Abnormal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_Abnormal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbnormalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_Abnormal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbnormalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_Abnormal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbnormalFlagParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_Abnormal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeFlagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_Abnormal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_Abnormal_proto_goTypes,
		DependencyIndexes: file_rpc_Abnormal_proto_depIdxs,
		MessageInfos:      file_rpc_Abnormal_proto_msgTypes,
	}.Build()
	File_rpc_Abnormal_proto = out.File
	file_rpc_Abnormal_proto_rawDesc = nil
	file_rpc_Abnormal_proto_goTypes = nil
	file_rpc_Abnormal_proto_depIdxs = nil
}
