// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: rpc/ffmpeg.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeFlagFfmpegResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   bool   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ChangeFlagFfmpegResponse) Reset() {
	*x = ChangeFlagFfmpegResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_ffmpeg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeFlagFfmpegResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeFlagFfmpegResponse) ProtoMessage() {}

func (x *ChangeFlagFfmpegResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ffmpeg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeFlagFfmpegResponse.ProtoReflect.Descriptor instead.
func (*ChangeFlagFfmpegResponse) Descriptor() ([]byte, []int) {
	return file_rpc_ffmpeg_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeFlagFfmpegResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ChangeFlagFfmpegResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VideoStreamStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RtspUrl []string `protobuf:"bytes,1,rep,name=rtsp_url,json=rtspUrl,proto3" json:"rtsp_url,omitempty"`
	RtmpUrl []string `protobuf:"bytes,2,rep,name=rtmp_url,json=rtmpUrl,proto3" json:"rtmp_url,omitempty"`
}

func (x *VideoStreamStruct) Reset() {
	*x = VideoStreamStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_ffmpeg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoStreamStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStreamStruct) ProtoMessage() {}

func (x *VideoStreamStruct) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ffmpeg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStreamStruct.ProtoReflect.Descriptor instead.
func (*VideoStreamStruct) Descriptor() ([]byte, []int) {
	return file_rpc_ffmpeg_proto_rawDescGZIP(), []int{1}
}

func (x *VideoStreamStruct) GetRtspUrl() []string {
	if x != nil {
		return x.RtspUrl
	}
	return nil
}

func (x *VideoStreamStruct) GetRtmpUrl() []string {
	if x != nil {
		return x.RtmpUrl
	}
	return nil
}

type VideoStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   bool     `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RtmpUrl []string `protobuf:"bytes,3,rep,name=rtmp_url,json=rtmpUrl,proto3" json:"rtmp_url,omitempty"`
}

func (x *VideoStreamResponse) Reset() {
	*x = VideoStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_ffmpeg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStreamResponse) ProtoMessage() {}

func (x *VideoStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ffmpeg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStreamResponse.ProtoReflect.Descriptor instead.
func (*VideoStreamResponse) Descriptor() ([]byte, []int) {
	return file_rpc_ffmpeg_proto_rawDescGZIP(), []int{2}
}

func (x *VideoStreamResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *VideoStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VideoStreamResponse) GetRtmpUrl() []string {
	if x != nil {
		return x.RtmpUrl
	}
	return nil
}

type FlagParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag bool `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *FlagParam) Reset() {
	*x = FlagParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_ffmpeg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlagParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagParam) ProtoMessage() {}

func (x *FlagParam) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ffmpeg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagParam.ProtoReflect.Descriptor instead.
func (*FlagParam) Descriptor() ([]byte, []int) {
	return file_rpc_ffmpeg_proto_rawDescGZIP(), []int{3}
}

func (x *FlagParam) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

var File_rpc_ffmpeg_proto protoreflect.FileDescriptor

var file_rpc_ffmpeg_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x66, 0x6d, 0x70, 0x65, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x18, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x6c, 0x61, 0x67,
	0x46, 0x66, 0x6d, 0x70, 0x65, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x49,
	0x0a, 0x11, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x74, 0x73, 0x70, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x72, 0x74, 0x73, 0x70, 0x55, 0x72, 0x6c, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x74, 0x6d, 0x70, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x74, 0x6d, 0x70, 0x55, 0x72, 0x6c, 0x22, 0x60, 0x0a, 0x13, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x72, 0x74, 0x6d, 0x70, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x72, 0x74, 0x6d, 0x70, 0x55, 0x72, 0x6c, 0x22, 0x1f, 0x0a, 0x09, 0x46,
	0x6c, 0x61, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x32, 0x80, 0x01, 0x0a,
	0x06, 0x46, 0x66, 0x6d, 0x70, 0x65, 0x67, 0x12, 0x39, 0x0a, 0x0b, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x1a, 0x14, 0x2e, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3b, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x66, 0x6d, 0x70,
	0x65, 0x67, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x0a, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x1a, 0x19, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x46,
	0x66, 0x6d, 0x70, 0x65, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_ffmpeg_proto_rawDescOnce sync.Once
	file_rpc_ffmpeg_proto_rawDescData = file_rpc_ffmpeg_proto_rawDesc
)

func file_rpc_ffmpeg_proto_rawDescGZIP() []byte {
	file_rpc_ffmpeg_proto_rawDescOnce.Do(func() {
		file_rpc_ffmpeg_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_ffmpeg_proto_rawDescData)
	})
	return file_rpc_ffmpeg_proto_rawDescData
}

var file_rpc_ffmpeg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_ffmpeg_proto_goTypes = []interface{}{
	(*ChangeFlagFfmpegResponse)(nil), // 0: ChangeFlagFfmpegResponse
	(*VideoStreamStruct)(nil),        // 1: VideoStreamStruct
	(*VideoStreamResponse)(nil),      // 2: VideoStreamResponse
	(*FlagParam)(nil),                // 3: FlagParam
}
var file_rpc_ffmpeg_proto_depIdxs = []int32{
	1, // 0: Ffmpeg.VideoStream:input_type -> VideoStreamStruct
	3, // 1: Ffmpeg.ChangeFfmpegFlag:input_type -> FlagParam
	2, // 2: Ffmpeg.VideoStream:output_type -> VideoStreamResponse
	0, // 3: Ffmpeg.ChangeFfmpegFlag:output_type -> ChangeFlagFfmpegResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_ffmpeg_proto_init() }
func file_rpc_ffmpeg_proto_init() {
	if File_rpc_ffmpeg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_ffmpeg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeFlagFfmpegResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_ffmpeg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoStreamStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_ffmpeg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_ffmpeg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlagParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_ffmpeg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_ffmpeg_proto_goTypes,
		DependencyIndexes: file_rpc_ffmpeg_proto_depIdxs,
		MessageInfos:      file_rpc_ffmpeg_proto_msgTypes,
	}.Build()
	File_rpc_ffmpeg_proto = out.File
	file_rpc_ffmpeg_proto_rawDesc = nil
	file_rpc_ffmpeg_proto_goTypes = nil
	file_rpc_ffmpeg_proto_depIdxs = nil
}
