// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: rpc/video.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BacktrackingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnomalyScore      float32 `protobuf:"fixed32,1,opt,name=anomaly_score,json=anomalyScore,proto3" json:"anomaly_score,omitempty"`
	AnomalyCameraName string  `protobuf:"bytes,2,opt,name=anomaly_camera_name,json=anomalyCameraName,proto3" json:"anomaly_camera_name,omitempty"`
}

func (x *BacktrackingResponse) Reset() {
	*x = BacktrackingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_video_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BacktrackingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktrackingResponse) ProtoMessage() {}

func (x *BacktrackingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktrackingResponse.ProtoReflect.Descriptor instead.
func (*BacktrackingResponse) Descriptor() ([]byte, []int) {
	return file_rpc_video_proto_rawDescGZIP(), []int{0}
}

func (x *BacktrackingResponse) GetAnomalyScore() float32 {
	if x != nil {
		return x.AnomalyScore
	}
	return 0
}

func (x *BacktrackingResponse) GetAnomalyCameraName() string {
	if x != nil {
		return x.AnomalyCameraName
	}
	return ""
}

type BacktrackingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CameraName string   `protobuf:"bytes,1,opt,name=camera_name,json=cameraName,proto3" json:"camera_name,omitempty"`
	Rmtp       string   `protobuf:"bytes,2,opt,name=rmtp,proto3" json:"rmtp,omitempty"`
	VideoPath  []string `protobuf:"bytes,3,rep,name=video_path,json=videoPath,proto3" json:"video_path,omitempty"`
}

func (x *BacktrackingRequest) Reset() {
	*x = BacktrackingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_video_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BacktrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktrackingRequest) ProtoMessage() {}

func (x *BacktrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktrackingRequest.ProtoReflect.Descriptor instead.
func (*BacktrackingRequest) Descriptor() ([]byte, []int) {
	return file_rpc_video_proto_rawDescGZIP(), []int{1}
}

func (x *BacktrackingRequest) GetCameraName() string {
	if x != nil {
		return x.CameraName
	}
	return ""
}

func (x *BacktrackingRequest) GetRmtp() string {
	if x != nil {
		return x.Rmtp
	}
	return ""
}

func (x *BacktrackingRequest) GetVideoPath() []string {
	if x != nil {
		return x.VideoPath
	}
	return nil
}

type BacktrackingFlagParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag bool `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *BacktrackingFlagParam) Reset() {
	*x = BacktrackingFlagParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_video_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BacktrackingFlagParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktrackingFlagParam) ProtoMessage() {}

func (x *BacktrackingFlagParam) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktrackingFlagParam.ProtoReflect.Descriptor instead.
func (*BacktrackingFlagParam) Descriptor() ([]byte, []int) {
	return file_rpc_video_proto_rawDescGZIP(), []int{2}
}

func (x *BacktrackingFlagParam) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

type BacktrackingFlagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   bool   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BacktrackingFlagResponse) Reset() {
	*x = BacktrackingFlagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_video_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BacktrackingFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktrackingFlagResponse) ProtoMessage() {}

func (x *BacktrackingFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktrackingFlagResponse.ProtoReflect.Descriptor instead.
func (*BacktrackingFlagResponse) Descriptor() ([]byte, []int) {
	return file_rpc_video_proto_rawDescGZIP(), []int{3}
}

func (x *BacktrackingFlagResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *BacktrackingFlagResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_video_proto protoreflect.FileDescriptor

var file_rpc_video_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6b, 0x0a, 0x14, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6e, 0x6f,
	0x6d, 0x61, 0x6c, 0x79, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0c, 0x61, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x2e,
	0x0a, 0x13, 0x61, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x5f, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61, 0x6e, 0x6f,
	0x6d, 0x61, 0x6c, 0x79, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x69,
	0x0a, 0x13, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6d, 0x74, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6d, 0x74, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x22, 0x2b, 0x0a, 0x15, 0x42, 0x61, 0x63,
	0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x46, 0x6c, 0x61, 0x67, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x4a, 0x0a, 0x18, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x9e, 0x01, 0x0a, 0x0c, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x69, 0x6e, 0x67, 0x12, 0x3f, 0x0a, 0x0c, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x69, 0x6e, 0x67, 0x12, 0x14, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x42, 0x61, 0x63, 0x6b,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x4d, 0x0a, 0x16, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x69, 0x6e, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x16,
	0x2e, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x46, 0x6c, 0x61,
	0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x19, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_video_proto_rawDescOnce sync.Once
	file_rpc_video_proto_rawDescData = file_rpc_video_proto_rawDesc
)

func file_rpc_video_proto_rawDescGZIP() []byte {
	file_rpc_video_proto_rawDescOnce.Do(func() {
		file_rpc_video_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_video_proto_rawDescData)
	})
	return file_rpc_video_proto_rawDescData
}

var file_rpc_video_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_video_proto_goTypes = []interface{}{
	(*BacktrackingResponse)(nil),     // 0: BacktrackingResponse
	(*BacktrackingRequest)(nil),      // 1: BacktrackingRequest
	(*BacktrackingFlagParam)(nil),    // 2: BacktrackingFlagParam
	(*BacktrackingFlagResponse)(nil), // 3: BacktrackingFlagResponse
}
var file_rpc_video_proto_depIdxs = []int32{
	1, // 0: Backtracking.Backtracking:input_type -> BacktrackingRequest
	2, // 1: Backtracking.BacktrackingChangeFlag:input_type -> BacktrackingFlagParam
	0, // 2: Backtracking.Backtracking:output_type -> BacktrackingResponse
	3, // 3: Backtracking.BacktrackingChangeFlag:output_type -> BacktrackingFlagResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_video_proto_init() }
func file_rpc_video_proto_init() {
	if File_rpc_video_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_video_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BacktrackingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_video_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BacktrackingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_video_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BacktrackingFlagParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_video_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BacktrackingFlagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_video_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_video_proto_goTypes,
		DependencyIndexes: file_rpc_video_proto_depIdxs,
		MessageInfos:      file_rpc_video_proto_msgTypes,
	}.Build()
	File_rpc_video_proto = out.File
	file_rpc_video_proto_rawDesc = nil
	file_rpc_video_proto_goTypes = nil
	file_rpc_video_proto_depIdxs = nil
}
